services:
  angular-frontend:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200"
    depends_on:
      - springboot-backend

  springboot-backend:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    container_name: springboot-backend
    ports:
      - "8100:8100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-database:3306/electricity_bill_management_system
      SPRING_DATASOURCE_USERNAME: dev # override the default root username
      SPRING_DATASOURCE_PASSWORD: dev@123 # override the default root password
    depends_on:
      - mysql-database

  mysql-database:
    image: mysql:9.2.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: Debjit@123
      MYSQL_DATABASE: electricity_bill_management_system
      MYSQL_USER: dev # create non-root user
      MYSQL_PASSWORD: dev@123 # password for non-root user
    volumes:
      - mysql-database-data:/var/lib/mysql

volumes:
  mysql-database-data:
